name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  # Manually running a workflow
  workflow_dispatch


jobs:

  check-bats-job:
    environment: Dev
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          path: main
          
      - name: Checkout data
        uses: actions/checkout@v3
        with:
          ref: data
          path: data
          
              
      - run: pwd
      - run: ls
      
      - name: ls data
        working-directory: ./data
        run: |
          pwd
          ls
      
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          # latest           
          python-version: "*"
       
      - run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      
      - name: ls scripts
        working-directory: ./main/scripts
        run: |
          pwd
          ls
      
      - name: pipenv install
        working-directory: ./main/scripts
        run: |
          pipenv install
          
      - name: pipenv graph
        working-directory: ./main/scripts
        run: |
          pipenv graph
          
      #------------------        
      - name: update_year_semester_current
        working-directory: ./main/scripts
        run: |
          pipenv run python update_year_semester_current.py
          
          
      - working-directory: ./main/scripts
        run:  |
           ls
          
      - name: copy old file
        working-directory: .
        run:  |
           pwd
           mkdir -p ./main/data/course/
           cp ./data/course/year_semester_list.json ./main/scripts/data/course/year_semester_list.json
           
      - working-directory: ./main/scripts/data
        run:  |
           ls
      
      #------------------       
      - name: update_year_semester_list
        working-directory: ./main/scripts
        run: |
          pipenv run python update_year_semester_list.py
          
      - working-directory: ./main/scripts/data
        run:  |
           ls  
      
      #------------------       
      - name: update_department_list
        working-directory: ./main/scripts
        run: |
          pipenv run python update_department_list.py
          
      - working-directory: ./main/scripts/data
        run:  |
           ls  
     
     #------------------       
      - name: update_rating_data
        working-directory: ./main/scripts
        env:
          database_host: ${{ secrets.DATABASE_HOST }} 
          database_database: ${{ secrets.DATABASE_DATABASE }} 
          database_user: ${{ secrets.DATABASE_USER }} 
          database_password: ${{ secrets.DATABASE_PASSWORD }} 
          
        run: |
          pipenv run python update_rating_data.py
          
      - working-directory: ./main/scripts/data
        run:  |
           ls  
           
     #------------------       
      - name: update_course_data
        working-directory: ./main/scripts
        run: |
          pipenv run python update_course_data.py
          
      - working-directory: ./main/scripts/data/course
        run:  |
           ls 
           
     #------------------       
      - name: merge_course_rating
        working-directory: ./main/scripts
        run: |
          pipenv run python merge_course_rating.py
          
      - working-directory: ./main/scripts/data/course
        run:  |
           ls 
      
    #------------------ 
      - name: copy old file
        working-directory: .
        run:  |
           pwd
           cp -r ./data/class-viewer ./main/scripts/data/class-viewer
        
      - name: update_version
        working-directory: ./main/scripts
        run: |
          pipenv run python update_version.py
          
      - working-directory: ./main/scripts/data/
        run:  |
           ls 
   #------------------    
      - working-directory: ./main/scripts/data/course
        run:  |
           cat ./112/1/701/course_data.json
   
   
   
   
   
